🗃️ Committing everything that changed 🗃️
root/.local/bin/run-os-update

diff --git a/root/.local/bin/run-os-update b/root/.local/bin/run-os-update
--- a/root/.local/bin/run-os-update
+++ b/root/.local/bin/run-os-update
@@ -54,24 +54,34 @@ __run_updater() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __kernel_ml() {
   local exitC=0
-  echo "switch to the newest kernel from elrepo"
-  for p in $(rpm -qa --queryformat "%{NAME}\n" | grep 'kernel' | sort -u); do rpm -ev --nodeps $p; done
-  yum install -y kernel-ml* || exitC=1
-  run_grub
+  local kernel="$(uname -r 2>/dev/null | grep -F 'elrepo')"
+  if [ -n "$kernel" ]; then
+    echo "You are already running kernel-ml: $kernel"
+  else
+    echo "switch to the newest kernel from elrepo"
+    for p in $(rpm -qa --queryformat "%{NAME}\n" | grep 'kernel' | sort -u); do rpm -ev --nodeps $p; done
+    yum install -y kernel-ml* || exitC=1
+    run_grub
+  fi
   exit $exitC
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __kernel_lt() {
   local exitC=0
-  echo "switch to the newest lts kernel from elrepo"
-  for p in $(rpm -qa --queryformat "%{NAME}\n" | grep 'kernel' | sort -u); do rpm -ev --nodeps $p; done
-  yum install -y kernel-lt* || exitC=1
-  run_grub
+  local kernel="$(uname -r 2>/dev/null | grep -F 'elrepo')"
+  if [ -n "$kernel" ]; then
+    echo "You are already running kernel-lt: $kernel"
+  else
+    echo "switch to the newest lts kernel from elrepo"
+    for p in $(rpm -qa --queryformat "%{NAME}\n" | grep 'kernel' | sort -u); do rpm -ev --nodeps $p; done
+    yum install -y kernel-lt* || exitC=1
+    run_grub
+  fi
   exit $exitC
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 run_grub() {
-  printf_green "Initializing grub configuration"
+  echo "Initializing grub configuration"
   local cfg="" efi="" grub_cfg="" grub_efi="" grub_bin="" grub_bin_name=""
   grub_cfg="$(find /boot/grub*/* -name 'grub*.cfg' | grep '^' || false)"
   grub_efi="$(find /boot/efi/EFI/* -name 'grub*.cfg' | grep '^' || false)"
@@ -82,14 +92,14 @@ run_grub() {
     if [ -n "$grub_cfg" ]; then
       for cfg in $grub_cfg; do
         if [ -e "$cfg" ]; then
-          devnull $grub_bin -o "$cfg" && printf_green "Updated $cfg" || printf_return "Failed to update $cfg"
+          devnull $grub_bin -o "$cfg" && echo "Updated $cfg" || echo "Failed to update $cfg"
         fi
       done
     fi
     if [ -n "$grub_efi" ]; then
       for efi in $grub_efi; do
         if [ -e "$efi" ]; then
-          devnull $grub_bin -o "$efi" && printf_green "Updated $efi" || printf_return "Failed to update $efi"
+          devnull $grub_bin -o "$efi" && echo "Updated $efi" || echo "Failed to update $efi"
         fi
       done
     fi
