🗃️  Committing everything that changed 🗃️

diff --git a/root/.local/bin/run-os-update b/root/.local/bin/run-os-update
--- a/root/.local/bin/run-os-update
+++ b/root/.local/bin/run-os-update
@@ -35,6 +35,7 @@ __save_remote_file() { curl -q -SLs "$1" | tee "$2" &>/dev/null || exit 1; }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 __repo_file() {
   local statusCode="0"
+  [ "$ARCH" = "x86_64" ] || return 0
   if [ "$RELEASE_VER" -ge "9" ]; then
     YUM_DELETE="no"
     RELEASE_FILE="https://github.com/rpm-devel/casjay-release/raw/main/casjay.rh9.repo"
@@ -69,6 +70,9 @@ __run_updater() {
 echo "$PATH" | grep -q "/root/.local/bin" || export PATH="/root/.local/bin:$PATH"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 DATE="$(date +'%y-%m-%d at %H:%M')"
+ARCH="$(uname -m | tr '[:upper:]' '[:lower:]')"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+export FORCE_INST="${FORCE_INST:-}"
 export TIME_ZONE="${TZ:-America/New_York}"
 export STATICSITE="${STATICSITE:-$(hostnamecli -f)}"
 export SERVICES_ENABLE="httpd nginx munin-node cockpit postfix "
@@ -77,14 +81,12 @@ export SERVICES_ENABLE+="uptimed downtimed php-fpm proftpd rsyslog chronyd snmpd
 export SERVICES_DISABLE="firewalld auditd kdump iscsid.socket lvm2-lvmpolld.socket lvm2-monitor "
 export SERVICES_DISABLE+="iscsi.service iscsiuio.socket lvm2-lvmetad.socket radvd "
 export SERVICES_DISABLE+="fail2ban shorewall shorewall6 named dhcpd dhcpd6 mdmonitor "
-export FORCE_INST="${FORCE_INST:-}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 export INSTALLED_VERSION="$(head -n1 <"/etc/casjaysdev/updates/versions/configs.txt" 2>/dev/null)"
 export REMOTE_VERSION="$(curl -q -LSsf "https://github.com/casjay-base/centos/raw/main/version.txt" | head -n1)"
-export RELEASE_VER="$(grep --no-filename -s 'VERSION_ID=' /etc/*-release | awk -F '=' '{print $2}' | sed 's#"##g' | awk -F '.' '{print $1}' | grep '^')"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-RELEASE_VER="$(grep --no-filename -s 'VERSION_ID=' /etc/*-release | awk -F '=' '{print $2}' | sed 's#"##g' | awk -F '.' '{print $1}' | grep '^')"
-RELEASE_NAME="$(grep --no-filename -s '^NAME=' /etc/*-release | awk -F'=' '{print $2}' | sed 's|"||g;s| .*||g' | tr '[:upper:]' '[:lower:]' | grep '^')"
+export RELEASE_VER="$(grep --no-filename -s 'VERSION_ID=' /etc/*-release | awk -F '=' '{print $2}' | sed 's#"##g' | awk -F '.' '{print $1}' | grep '^')"
+export RELEASE_NAME="$(grep --no-filename -s '^NAME=' /etc/*-release | awk -F'=' '{print $2}' | sed 's|"||g;s| .*||g' | tr '[:upper:]' '[:lower:]' | grep '^')"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 hostnamefull="$(hostname -f 2>/dev/null || echo "$HOSTNAME")"
 hostnameshort="$(hostname -s 2>/dev/null || echo "$HOSTNAME")"
@@ -141,10 +143,10 @@ else
 
   echo -e "Updating yum repos for $RELEASE_NAME $RELEASE_VER"
   if ! __repo_file; then
-    echo -e "Failed to update the repos"
+    echo -e "Failed to update the repos\n"
     exit 1
   fi
-  echo -e "Done updating yum repos for $RELEASE_NAME $RELEASE_VER"
+  echo -e "Done updating yum repos for $RELEASE_NAME $RELEASE_VER\n"
 
   echo -e "Setting up packages - this may take some time!"
   yum update -yy -q &>/dev/null
